apiVersion: v1
kind: Secret
metadata:
  name: pkt-secrets
  namespace: packetcrypt
data:
  # base64 encoded address of your wallet
  wallet: base64Wallet
  # base64 encoded pool address; default -> http://pool.pktpool.io
  pool: aHR0cDovL3Bvb2wucGt0cG9vbC5pbwo=
  # The public wallet password -- Only required if the wallet was created with one
  # Set to 'Cg==' (empty base64) if you have to passphrase set.
  wallet-public-passphrase: Cg==
type: Opaque
